config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "about", to: "welcome#about"
  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in first to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Ariticle was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only update and delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
    else
      render "new"
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to categories_path
    else
      render "edit"
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end

  def set_category
      @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfull logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something is wrong with your login information"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:danger] = "User was successfully deleted"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit your own profile"
        redirect_to users_path
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #gravatar_size = size
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="col-xs-offset-2 col-xs-8">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.description, length: 100) %>
        <% if article.categories.any? %>
          <p><%= render article.categories %></p>
        <% end %>
        <div class="article-meta">
          <small>
            Created by: <%= article.user.username if article.user %>
            , <%= time_ago_in_words(article.created_at) %> ago
            , last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
      </div>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-action">
          <%= link_to 'Edit the article', edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Delete the article', article_path(article),
                                            method: :delete,
                                            data: {confirm: "Are sure you want to delete this article?"},
                                            class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter article title",
                                autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_area :description, rows: "10", class: "form-control", placeholder: "Enter article description" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox") { cb.check_box + cb.text } %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit class: "btn btn-danger btn-md" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>

<%= render 'form' %>

<p class="text-center">[ <%= link_to 'Return to article listing', articles_path %> ]</p>

app/views/articles/index.html.erb
<h1 align="center">Article listing</h1>
<div class="text-center">
  <%= will_paginate %>
</div>
<%= render 'articles', obj: @articles %>
<div class="text-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create new article</h1>

<%= render 'form' %>

<p class="text-center">[ <%= link_to 'Return to article listing', articles_path %> ]</p>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-offset-2 col-xs-8">
  <% if @article.user %>
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
      <div class="text-center">
        <ul class="listing">
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if !@article.user.articles.empty? %></small></li>
        </ul>
      </div>
    </div>
  </div>
  <% end %>
  <h4 class="text-center description">Description:</h4>
  <hr>
  <span class="text-justify"><%= simple_format(@article.description) %><span>
  <% if @article.categories.any? %>
    <p><%= render @article.categories %></p>
  <% end %>
  <div class="article-action">
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to 'Edit the article', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to 'Delete the article', article_path(@article),
                                      method: :delete,
                                      data: {confirm: "Are sure you want to delete this article?"},
                                      class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<small class="label label-info"><%= link_to category.name, category_path(category) %></small>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <%= f.label :name, class: "control-label col-sm-2" %>
  <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter category name",
                            autofocus: true %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-8">
    <%= f.submit class: "btn btn-danger btn-md" %>
  </div>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit category name</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1 align="center">Category list</h1>

<div class="text-center">
  <%= will_paginate %>
</div>

<% @categories.each do |category| %>
<div class="row">
  <div class="well col-xs-offset-4 col-xs-4 text-center">
    <div class="article-title">
      <%= link_to category.name, category_path(category) %>
    </div>
    <p><small><%= pluralize(category.articles.count, "article") %></small></p>
  </div>
</div>
<% end %>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>

<div class="text-center">
  <% if logged_in? && current_user.admin? %>
    <p><%= link_to "Edit category name", edit_category_path %></p>
  <% end %>
  <%= will_paginate @category_articles %>
</div>

<%= render "articles/articles", obj: @category_articles %>

<div class="text-center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer>
    <small>Copyright&copy; <a href="https://github.com/xbrny">bani</a> alpha blog</small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path, class: "btn btn-xs"  %></li>
        <li><%= link_to "About", about_path, class: "btn btn-xs" %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
    <div class='alert alert-<%= "#{name}" %>' role="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>
        <%= msg %>
        <%# <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </strong>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create category", new_category_path %></li>
            <% end %>
          </ul>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Profile <%= "Admin" if current_user.admin? %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%# debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-10 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited article from being saved
        </h2>
      </div>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <%= f.label :username, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username",
                                autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit(@user.new_record? ? "Signup" : "Update account", class: "btn btn-danger btn-md") %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Update account</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center">User listing</h1>

<div class="text-center">
  <%= will_paginate %>
</div>

<% @users.each do |user| %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="well text-center">
      <ul class="listing">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li><%= link_to user.username, user_path(user) %></li>
        <li><small><%= pluralize(user.articles.count, "article") if !user.articles.empty? %></small></li>
        <% if logged_in? && current_user.admin? %>
        <li><%= link_to "Delete", user_path(user), method: :delete,
                data: { confirm: "Are you sure you want to delete this user and all their articles?"} %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
    <div class="col-xs-offset-4 col-xs-4 text-center">
      <%= gravatar_for @user %>
    </div>
</div>

<h3 class="text-center"><%= @user.username %>'s articles</h3>

<div class="text-center">
  <%= will_paginate @user_articles %>
</div>

<%= render "articles/articles", obj: @user_articles %>

<div class="text-center">
  <%= will_paginate @user_articles %>
</div>

app/views/welcome/about.html.erb
<h1 align="center">About</h1>
<div class="col-xs-offset-2 col-xs-8">
  <p class="text-center">Alpha blog is project for my ruby on rails course on udemy,
  this website allows user to create read update and delete articles</p>
</div>

app/views/welcome/index.html.erb
<div class="text-center jumbotron">
  <h1>Welcome to Alpha Blog</h1>
  <p>Check out our <%= link_to "awesome article", articles_path, class: "text-danger" %></p>
  <%= link_to "Sign up", signup_path, class: "btn btn-xlarge btn-danger" %>
</div>